-- Primeiro, remover todas as tabelas se já existirem

DROP TABLE REPAROS CASCADE CONSTRAINTS;
DROP TABLE MANUTENCOES CASCADE CONSTRAINTS;
DROP TABLE SOLICITACOES_SERVICO CASCADE CONSTRAINTS;
DROP TABLE CARROS CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE TIPOS_SERVICO CASCADE CONSTRAINTS;

-- Tabela USUARIOS
CREATE TABLE USUARIOS (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identificador único do usuário
                          nome VARCHAR2(255) NOT NULL, -- Nome do usuário
                          senha VARCHAR2(255) NOT NULL, -- Senha do usuário
                          cpf VARCHAR2(11) NOT NULL UNIQUE, -- CPF do usuário
                          email VARCHAR2(255) NOT NULL UNIQUE -- E-mail do usuário
);

-- Tabela CARROS
CREATE TABLE CARROS (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identificador único do carro
                        modelo VARCHAR2(255) NOT NULL, -- Modelo do carro
                        ano NUMBER(4) NOT NULL, -- Ano de fabricação do carro
                        placa VARCHAR2(10) NOT NULL UNIQUE, -- Placa do carro
                        usuarioId NUMBER NOT NULL, -- ID do usuário proprietário do carro
                        CONSTRAINT fk_usuario FOREIGN KEY (usuarioId) REFERENCES USUARIOS(id) -- Chave estrangeira referenciando USUARIOS
);

-- Tabela MANUTENCOES
CREATE TABLE MANUTENCOES (
                             id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identificador único da manutenção
                             descricao VARCHAR2(255) NOT NULL, -- Descrição da manutenção
                             data DATE NOT NULL, -- Data da manutenção
                             carroId NUMBER NOT NULL, -- ID do carro relacionado à manutenção
                             detalhes VARCHAR2(500), -- Detalhes adicionais sobre a manutenção
                             CONSTRAINT fk_carro FOREIGN KEY (carroId) REFERENCES CARROS(id) -- Chave estrangeira referenciando CARROS
);

-- Tabela REPAROS
CREATE TABLE REPAROS (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identificador único do reparo
                         carroId NUMBER NOT NULL, -- ID do carro relacionado ao reparo
                         problema VARCHAR2(255) NOT NULL, -- Descrição do problema que gerou o reparo
                         status VARCHAR2(50) NOT NULL, -- Status do reparo (ex: Pendente, Em Andamento, Concluído)
                         CONSTRAINT fk_carro_reparo FOREIGN KEY (carroId) REFERENCES CARROS(id) -- Chave estrangeira referenciando CARROS
);

-- Tabela SOLICITACOES_SERVICO
CREATE TABLE SOLICITACOES_SERVICO (
                                      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identificador único da solicitação
                                      usuarioId NUMBER NOT NULL, -- ID do usuário que fez a solicitação
                                      descricao VARCHAR2(255) NOT NULL, -- Descrição da solicitação
                                      status VARCHAR2(50) DEFAULT 'Pendente', -- Status da solicitação (Pendente, Concluída, etc.)
                                      dataSolicitacao DATE DEFAULT SYSDATE, -- Data da solicitação
                                      CONSTRAINT fk_usuario_solicitacao FOREIGN KEY (usuarioId) REFERENCES USUARIOS(id) -- Chave estrangeira referenciando USUARIOS
);

-- Tabela TIPOS_SERVICO (Opcional - Se houver tipos diferentes de serviço)
CREATE TABLE TIPOS_SERVICO (
                               id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identificador único do tipo de serviço
                               nome VARCHAR2(255) NOT NULL UNIQUE -- Nome do tipo de serviço (ex: Revisão, Guincho, Reparo, etc.)
);